### PR TITLE
package-ify

### PR DESCRIPTION
**Pull request by msachtler**
Pretty rough cut at making these pip-installable.

I think there's (at least?) two ways to go about this; either make this all one big package, or make each subdirectory a package. I went with the latter here to make it more fine-grained, but that necessitated pushing the source one level deeper. It'd be easy to make this all one mega-package as well, let me know if you have a strong preference.

I also haven't filled out all the possible metadata, there's tons more that can be specified (e.g. https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html)

Installing pduSynaccess:
```
❯ venv/bin/pip install git+https://github.com/msachtler/pypascal/@packageify#subdirectory=pduSynaccess
Collecting git+https://github.com/msachtler/pypascal/@packageify#subdirectory=pduSynaccess
  Cloning https://github.com/msachtler/pypascal/ (to revision packageify) to /private/var/folders/bl/7p28nd850pbg1z8yy7bd2kd40000gn/T/pip-req-build-nh_7f0q4
  Running command git clone --filter=blob:none --quiet https://github.com/msachtler/pypascal/ /private/var/folders/bl/7p28nd850pbg1z8yy7bd2kd40000gn/T/pip-req-build-nh_7f0q4
  Running command git checkout -b packageify --track origin/packageify
  Switched to a new branch 'packageify'
  Branch 'packageify' set up to track remote branch 'packageify' from 'origin'.
  Resolved https://github.com/msachtler/pypascal/ to commit c4ee20b485477d6f9f689694fbfdbf1a9b7bf40a
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pyserial
  Using cached pyserial-3.5-py2.py3-none-any.whl (90 kB)
Building wheels for collected packages: pduSynaccess
  Building wheel for pduSynaccess (pyproject.toml) ... done
  Created wheel for pduSynaccess: filename=pduSynaccess-0.0.1-py3-none-any.whl size=4157 sha256=37e180b28072f29887b246268177a6b9ee135edf05cc65382eab178f981f7117
  Stored in directory: /private/var/folders/bl/7p28nd850pbg1z8yy7bd2kd40000gn/T/pip-ephem-wheel-cache-8qtaaux1/wheels/c7/e5/ac/c064e36c6ea1ef49bfd7ba7a3cda5a29fc669609f079010aef
Successfully built pduSynaccess
Installing collected packages: pyserial, pduSynaccess
Successfully installed pduSynaccess-0.0.1 pyserial-3.5
WARNING: There was an error checking the latest version of pip.

❯ venv/bin/python3
Python 3.9.13 (main, May 19 2022, 14:10:54) 
[Clang 13.1.6 (clang-1316.0.21.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pduSynaccess.pduSynaccess import pdu
>>> pdu.
pdu.command(    pdu.get(        pdu.mro(        pdu.off(        pdu.on(         pdu.operation(  pdu.set(
```

influxSender:
```
❯ venv/bin/pip install git+https://github.com/msachtler/pypascal/@packageify#subdirectory=influxSender
Collecting git+https://github.com/msachtler/pypascal/@packageify#subdirectory=influxSender
  Cloning https://github.com/msachtler/pypascal/ (to revision packageify) to /private/var/folders/bl/7p28nd850pbg1z8yy7bd2kd40000gn/T/pip-req-build-xyt4w4q1
  Running command git clone --filter=blob:none --quiet https://github.com/msachtler/pypascal/ /private/var/folders/bl/7p28nd850pbg1z8yy7bd2kd40000gn/T/pip-req-build-xyt4w4q1
  Running command git checkout -b packageify --track origin/packageify
  Switched to a new branch 'packageify'
  Branch 'packageify' set up to track remote branch 'packageify' from 'origin'.
  Resolved https://github.com/msachtler/pypascal/ to commit 763d21594757cb24834c47a787fb2867a85c24ef
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting influxdb
  Using cached influxdb-5.3.1-py2.py3-none-any.whl (77 kB)
Collecting pytz
  Using cached pytz-2022.1-py2.py3-none-any.whl (503 kB)
Collecting six>=1.10.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting msgpack
  Using cached msgpack-1.0.3-cp39-cp39-macosx_10_9_x86_64.whl (75 kB)
Collecting python-dateutil>=2.6.0
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting requests>=2.17.0
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.5.18.1-py3-none-any.whl (155 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Building wheels for collected packages: influxSender
  Building wheel for influxSender (pyproject.toml) ... done
  Created wheel for influxSender: filename=influxSender-0.0.1-py3-none-any.whl size=3862 sha256=c41f846dc90c52bdfa5ce7990cbf71fe223aa2f6b416c6cfb6ead35965e544c3
  Stored in directory: /private/var/folders/bl/7p28nd850pbg1z8yy7bd2kd40000gn/T/pip-ephem-wheel-cache-aghsuh1e/wheels/77/2d/e5/538b71ccc9ab1311a7cc74d8ec20d6b4023897a8d8f8b15f2c
Successfully built influxSender
Installing collected packages: pytz, msgpack, urllib3, six, idna, charset-normalizer, certifi, requests, python-dateutil, influxdb, influxSender
Successfully installed certifi-2022.5.18.1 charset-normalizer-2.0.12 idna-3.3 influxSender-0.0.1 influxdb-5.3.1 msgpack-1.0.3 python-dateutil-2.8.2 pytz-2022.1 requests-2.27.1 six-1.16.0 urllib3-1.26.9
WARNING: There was an error checking the latest version of pip.

❯ venv/bin/python3
Python 3.9.13 (main, May 19 2022, 14:10:54) 
[Clang 13.1.6 (clang-1316.0.21.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from influxSender.influxSender import InfluxSender
>>> InfluxSender.
InfluxSender.close(            InfluxSender.mro(              InfluxSender.sendDict(         InfluxSender.timestamp(        
InfluxSender.dict2lineformat(  InfluxSender.open(             InfluxSender.sendPoints(       InfluxSender.timestamp_ns(     
```

fpgacomm:
```
❯ venv/bin/pip install git+https://github.com/msachtler/pypascal/@packageify#subdirectory=fpgacomm
Collecting git+https://github.com/msachtler/pypascal/@packageify#subdirectory=fpgacomm
  Cloning https://github.com/msachtler/pypascal/ (to revision packageify) to /private/var/folders/bl/7p28nd850pbg1z8yy7bd2kd40000gn/T/pip-req-build-bknq6rgy
  Running command git clone --filter=blob:none --quiet https://github.com/msachtler/pypascal/ /private/var/folders/bl/7p28nd850pbg1z8yy7bd2kd40000gn/T/pip-req-build-bknq6rgy
  Running command git checkout -b packageify --track origin/packageify
  Switched to a new branch 'packageify'
  Branch 'packageify' set up to track remote branch 'packageify' from 'origin'.
  Resolved https://github.com/msachtler/pypascal/ to commit 763d21594757cb24834c47a787fb2867a85c24ef
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pyserial
  Using cached pyserial-3.5-py2.py3-none-any.whl (90 kB)
Building wheels for collected packages: fpgacomm
  Building wheel for fpgacomm (pyproject.toml) ... done
  Created wheel for fpgacomm: filename=fpgacomm-0.0.1-py3-none-any.whl size=3679 sha256=7a543eb7e413ea26492b47ffab97f2a663c22455ccccf4d1dfd8dc8d446138a3
  Stored in directory: /private/var/folders/bl/7p28nd850pbg1z8yy7bd2kd40000gn/T/pip-ephem-wheel-cache-f5r40hyc/wheels/89/65/45/458e1c2d5341ab5dd214e6f9760f3f5484aff5a7e411b05ee7
Successfully built fpgacomm
Installing collected packages: pyserial, fpgacomm
Successfully installed fpgacomm-0.0.1 pyserial-3.5
WARNING: There was an error checking the latest version of pip.

❯ venv/bin/python3
Python 3.9.13 (main, May 19 2022, 14:10:54) 
[Clang 13.1.6 (clang-1316.0.21.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from fpgacomm.fpgacomm import fpgacomm
>>> fpgacomm.
fpgacomm.close(        fpgacomm.mro(          fpgacomm.open(         fpgacomm.regRead(      fpgacomm.regWrite(     fpgacomm.serialRead(   fpgacomm.serialWrite(

```

### CODE REVIEW

**Comment by msachtler** [comment]
I think this is the principled way to avoid the double import:  https://gist.github.com/CMCDragonkai/510ce9456a0429f616baa243d1de3dbf

**Comment by msachtler** [comment]
With 3f5d175: 

```
❯ venv/bin/python3
Python 3.9.13 (main, May 19 2022, 14:10:54) 
[Clang 13.1.6 (clang-1316.0.21.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import fpgacomm
>>> import influxSender
i>>> import pduSynaccess
>>> dir(fpgacomm.fpgacomm)
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'close', 'open', 'regRead', 'regWrite', 'serialRead', 'serialWrite']
>>> dir(influxSender.InfluxSender)
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'close', 'dict2lineformat', 'open', 'sendDict', 'sendPoints', 'timestamp', 'timestamp_ns']
>>> dir(pduSynaccess.pdu)
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'command', 'get', 'off', 'on', 'operation', 'set']
```

**Comment by pstang** [comment]
Hey Matt, I adopted your packageify stuff and expanded to the rest of the repo -- thanks!
Since the PR comes from your fork, I wasn't sure how to add commits to it before merging, so I cherrypicked your commits back to mine.

Four things I was curious about that I'll have to look into later:
1) We have both pyproject,toml and setup.cfg.  Is it typical to use both rather than one or the other?
2) Look at the double-nesting of module directories.  Can one of them become "src"?
3) The "from .module import module" was interesting.  I agree I want to do the usual "import module" then "inst = module.class(args)".  I didn't realize there would be an additional level of indirection.
4) A few of my modules are eventually meant to contain a base API with implementation specializations, like ptu.flir and ptu.newport.  I'm definitely setting things up wrong for this goal -- the module name should be the general one, e.g. "ptu" or "pantilt" or something.

**Comment by msachtler** [comment]
OK - closing this PR. There's definitely improvements to keep making; we can discuss offline.

**Pull request closed without merging**
